apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-logger
  template:
    metadata:
      labels:
        app: fake-logger
    spec:
      containers:
      - name: fake-logger
        image: sriharik22/fake-logger:latest
        imagePullPolicy: Always
